swarm:
  restart: always
  image: swarm
  extra-hosts:
    - "jupyterhub:${JUPYTERHUB_HOST}"
  command: "join --advertise=${IP_ADDR}:2375 consul://jupyterhub:8500"

telegraf:
  restart: always
  image: telegraf:latest
  environment:
    HOST_PROC: /rootfs/proc
    HOST_SYS: /rootfs/sys
    HOST_ETC: /rootfs/etc
  hostname: jade-slave-${ENVIRONMENT}
  volumes:
   - /usr/local/share/jade/docker/slave/telegraf.conf:/etc/telegraf/telegraf.conf:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - /sys:/rootfs/sys:ro
   - /proc:/rootfs/proc:ro
   - /etc:/rootfs/etc:ro
